### ISSUE TITLE
Load syntax highlighting options

### ISSUE THREAD

**Issue by Ahmad-Bamba** [Alexbay218/nste#3]
Since this is a lightweight application, it may not be desirable to support syntax highlighting for every programming language in existence. However, if users could define syntax highlighting rules themselves, they could have the option of loading them into the application, providing functionality while still keeping the minimalism of the application.

**Comment by Alexbay218** [comment]
This was an idea that was going to be implemented anyways

**Comment by Alexbay218** [comment]
Done
